# permissions for end users to view httpfilters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: httpfilter-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: envoy-xds-controller
    app.kubernetes.io/part-of: envoy-xds-controller
    app.kubernetes.io/managed-by: kustomize
  name: httpfilter-viewer-role
rules:
- apiGroups:
  - envoy.kaasops.io
  resources:
  - httpfilters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - envoy.kaasops.io
  resources:
  - httpfilters/status
  verbs:
  - get
