apiVersion: envoy.kaasops.io/v1alpha1
kind: Listener
metadata:
  name: "https"
spec:
  name: "https"
  enable_reuse_port: false    # Only foc MacOS
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 443
  listener_filters:
    - name: "envoy.filters.listener.tls_inspector" 
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
---
apiVersion: envoy.kaasops.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  name: cluster-sample
  connect_timeout: 1s
  lb_policy: LEAST_REQUEST
  type: STATIC
  load_assignment:
    cluster_name: cluster-sample
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 80
---
apiVersion: envoy.kaasops.io/v1alpha1
kind: VirtualService
metadata:
  name: virtualservice-sample
spec:
  virtualHost:
    name: vh-test
    domains:
    - "example.io"
    routes:
    - match: 
        prefix: "/"
      route: 
        cluster: cluster-sample
  tlsConfig:
    secretRef:
      name: cert1
      namespace: default
  accessLog:
    name: envoy.access_loggers
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      path: /tmp/access_log
      log_format: 
        json_format: 
          timestamp: "%START_TIME%"
          verison: "%PROTOCOL%"
          request_time: "%DURATION%"
          status: "%RESPONSE_CODE%"
          response_flags: "%RESPONSE_FLAGS%"
          upstream: "%UPSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
          upstream_cluster: "%UPSTREAM_CLUSTER%"
          real-host: "%REQ(ORIGINAL-HOST)%"
          host: "%REQ(:AUTHORITY)%"
          response_code_details: "%RESPONSE_CODE_DETAILS%"
          real-ip: "%REQ(REAL-IP)%"
          request: "%REQ(:PATH)%"
          serverip: "%DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%"
          server_port: "%DOWNSTREAM_LOCAL_PORT%"
          server_protocol: "%PROTOCOL%"
          sni: "%REQUESTED_SERVER_NAME%"
          ssl_cipher: "%DOWNSTREAM_TLS_CIPHER%"
          ssl_protocol: "%DOWNSTREAM_TLS_VERSION%"
          hostname: "%HOSTNAME%"
          method: "%REQ(:METHOD)%"
          user_agent: "%REQ(USER-AGENT)%"
          request_id: "%REQ(X-REQUEST-ID)%"
          scheme: "%REQ(:SCHEME)%"
          http_referer: "%REQ(REFERER)%"
          x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
          x_requested_with: "%REQ(X-REQUESTED-WITH)%"
          envoy_response_flags: "%RESPONSE_FLAGS%"
          location_id: "%REQ(LOCATION-ID)%"
          upstream_response_time: "%RESPONSE_DURATION%"
          upstream_failure: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
          balancer: "envoy"
  listener:
    name: https
    namespace: default
---