apiVersion: envoy.kaasops.io/v1alpha1
kind: Listener
metadata:
  labels:
    app.kubernetes.io/name: listener
    app.kubernetes.io/instance: listener-sample
    app.kubernetes.io/part-of: envoy-xds-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: envoy-xds-controller
  name: default-https
spec:
  name: default-https
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9443
  listener_filters:
    - name: "envoy.filters.listener.tls_inspector" 
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector  