apiVersion: envoy.kaasops.io/v1alpha1
kind: Listener
metadata:
  labels:
    app.kubernetes.io/name: listener
    app.kubernetes.io/instance: listener-sample
    app.kubernetes.io/part-of: envoy-xds-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: envoy-xds-controller
  name: listener-sample
spec:
  # TODO(user): Add fields here
