apiVersion: envoy.kaasops.io/v1alpha1
kind: Upstream
metadata:
  labels:
    app.kubernetes.io/name: upstream
    app.kubernetes.io/instance: upstream-sample
    app.kubernetes.io/part-of: envoy-xds-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: envoy-xds-controller
  name: upstream-sample
spec:
  # TODO(user): Add fields here
