apiVersion: envoy.kaasops.io/v1alpha1
kind: Listener
metadata:
  name: "https"
  namespace: envoy-xds-controller
spec:
  name: "https"
  enable_reuse_port: false    # Only foc MacOS
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 443
  listener_filters:
    - name: "envoy.filters.listener.tls_inspector" 
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector  
