name: Tests
on:
  push:
    branches:
    - "main"
    tags:
      - 'v*'
  pull_request:
    branches:
    - "main"
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  conformance-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read   #  for actions/checkout
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: ./tools/github-actions/setup-deps
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Run Conformance Tests
      run: make conformance
  e2e-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read   #  for actions/checkout
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: ./tools/github-actions/setup-deps
    - name: Run E2e Tests
      run: make e2e